/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthGuideRouteImport } from './routes/_auth/guide'
import { Route as AuthInicioRouteImport } from './routes/_auth/inicio'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthSupportRouteImport } from './routes/_auth/support'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthAdminAuditRouteImport } from './routes/_auth/admin/audit'
import { Route as AuthAdminRolesRouteImport } from './routes/_auth/admin/roles'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth/admin/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGuideRoute = AuthGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInicioRoute = AuthInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSupportRoute = AuthSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminAuditRoute = AuthAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRolesRoute = AuthAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof AuthGuideRoute
  '/inicio': typeof AuthInicioRoute
  '/profile': typeof AuthProfileRoute
  '/support': typeof AuthSupportRoute
  '/admin/audit': typeof AuthAdminAuditRoute
  '/admin/roles': typeof AuthAdminRolesRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/admin/': typeof AuthAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide': typeof AuthGuideRoute
  '/inicio': typeof AuthInicioRoute
  '/profile': typeof AuthProfileRoute
  '/support': typeof AuthSupportRoute
  '/admin/audit': typeof AuthAdminAuditRoute
  '/admin/roles': typeof AuthAdminRolesRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/admin': typeof AuthAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/guide': typeof AuthGuideRoute
  '/_auth/inicio': typeof AuthInicioRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/support': typeof AuthSupportRoute
  '/_auth/admin/audit': typeof AuthAdminAuditRoute
  '/_auth/admin/roles': typeof AuthAdminRolesRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/inicio'
    | '/profile'
    | '/support'
    | '/admin/audit'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guide'
    | '/inicio'
    | '/profile'
    | '/support'
    | '/admin/audit'
    | '/admin/roles'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/guide'
    | '/_auth/inicio'
    | '/_auth/profile'
    | '/_auth/support'
    | '/_auth/admin/audit'
    | '/_auth/admin/roles'
    | '/_auth/admin/users'
    | '/_auth/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/guide': {
      id: '/_auth/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthGuideRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inicio': {
      id: '/_auth/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthInicioRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/support': {
      id: '/_auth/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthSupportRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/audit': {
      id: '/_auth/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthAdminAuditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/roles': {
      id: '/_auth/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthAdminRolesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthGuideRoute: typeof AuthGuideRoute
  AuthInicioRoute: typeof AuthInicioRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthSupportRoute: typeof AuthSupportRoute
  AuthAdminAuditRoute: typeof AuthAdminAuditRoute
  AuthAdminRolesRoute: typeof AuthAdminRolesRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGuideRoute: AuthGuideRoute,
  AuthInicioRoute: AuthInicioRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthSupportRoute: AuthSupportRoute,
  AuthAdminAuditRoute: AuthAdminAuditRoute,
  AuthAdminRolesRoute: AuthAdminRolesRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
